### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by guanrenxue** [fanfanda/Medical-Image-Fusion#2]
Hello, I am very interested in your research content, directly using the model you provided for testing, but there are problems, such as:
(cenet) renxue@dell:~/Medical-Image-Fusion$ python predict.py data/case10/ct1_012.gif data/case10/mr2_012.gif
Traceback (most recent call last):
   File "predict.py", line 34, in <module>
     Img_ct = transform(img_ct)
   File "/home/renxue/anaconda3/envs/cenet/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
     Img = t(img)
   File "/home/renxue/anaconda3/envs/cenet/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 76, in __call__
     Return F.to_tensor(pic)
   File "/home/renxue/anaconda3/envs/cenet/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 48, in to_tensor
     Img = torch.from_numpy(pic.transpose((2, 0, 1)))
ValueError: axes don't match array
How can I solve this? I look forward to your reply and wish you a happy life.

**Comment by fanfanda** [comment]
In my test environment, everything is ok. Can you output the shape of the read image before the transform function?
